### ISSUE TITLE
struct.error: unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by gcwarner1** [ntopper/RHD.py#1]
My code:

```
import RHD

dir = '/transform/gcw8/Ephys_Test/Data/TestMouse2_150423_133802.rhd'

data = RHD.openRhd(dir)
header = data.readHead()
print header
```

Is giving the error:

```
Traceback (most recent call last):
  File "intan_test.py", line 6, in <module>
    header = data.readHead()
  File "/transform/anaconda/lib/python2.7/site-packages/RHD.py", line 38, in readHead
    self.header_identifier = hex(np.uint32(struct.unpack('<I', self.rhd.read(4))))
struct.error: unpack requires a string argument of length 4
```

It's a normal, uncorrupted .rhd file which leads me to believe this might be a bug.

**Comment by ntopper** [comment]
the readHead is not meant to be called outside of the constructor. It reads specific bytes from the beginning of the file. The constructor reads in all data to the end of the file, thus calling readHead outside of the constructor causes the module to read in more data, past the end of the file. 

All data from the header is stored in instance variables with the following names:

```
actual_dsp_cutoff_frequency
actual_impedance_test_frequency
actual_lower_bandwidth
actual_upper_bandwidth
board_mode
channels
data_block_list
desired_dsp_cutoff_frequency
desired_impedance_test_frequency
desired_lower_bandwidth
desired_upper_bandwidth
dsp_enabled
header_identifier
notch_cutoff_mode
note
number_of_signal_groups
number_of_temperature_sensors
sample_rate
signal_groups
version
```

For example, if you wanted the sample rate and board mode from your RHD object, your code would look something like this:    

```
import RHD

dir = '/transform/gcw8/Ephys_Test/Data/TestMouse2_150423_133802.rhd'

data = RHD.openRhd(dir)

print "Sample Rate: " + str(data.sample_rate) + " Hz"
print "Board Mode: " + str(data.board_mode)
```

In retrospect it may have been useful to organize all the header data into a dictionary so that it is iterable. I may add this soon.

**Comment by gcwarner1** [comment]
OK this makes sense. Thank you. So to get the number of samples would I do `len(data.data_block_list)`?
